server:
  port: 8089

spring:
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    org.hibernate.orm.jdbc.bind: trace